import { useEffect } from "react";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import ConfirmationCard from "@/components/ConfirmationCard";
import { useAppContext } from "@/context/global";

const ConfirmationPage: NextPage = () => {
  const router = useRouter();

  const { transaction } = useAppContext();

  useEffect(() => {
    if (!transaction.input.iconUrl || !transaction.output.iconUrl) {
      router.push("/swap");
    }
  }, []);

  return (
    <>
      <Head>
        <title>Belo | Confirmation</title>
        {/* <meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <ConfirmationCard />
      </div>
    </>
  );
};

export default ConfirmationPage;
