import type { NextPage } from "next";
import Head from "next/head";
import ConfirmationCard from "../components/ConfirmationCard";

const ConfirmationPage: NextPage = () => (
  <>
    <Head>
      <title>Belo | Confirmation</title>
      {/* <meta name="description" content="Generated by create next app" />*/}
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container mx-auto">
      <ConfirmationCard />
    </div>
  </>
);

export default ConfirmationPage;
