import type { NextPage } from "next";
import Head from "next/head";
import TableCoins from "@/components/TableCoins";
import fetchData from "@/helpers/fetchData";
import { Coin } from "@/services/transforms/coins";

interface Props {
  coins: Coin[];
}

const HomePage: NextPage<Props, any> = ({ coins }) => {
  return (
    <>
      <Head>
        <title>Belo | Home</title>
        {/* <meta name="description" content="Generated by create next app" />*/}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <TableCoins coins={coins} />
      </div>
    </>
  );
};

export async function getServerSideProps() {
  const response = await fetchData({
    method: "GET",
    url: `/api/coins`,
  });

  return { props: { coins: response.data } };
}

export default HomePage;
