import type { NextPage } from "next";
import Head from "next/head";
import TableSwap from "../components/TableSwap";

const Swap: NextPage = () => (
  <>
    <Head>
      <title>Belo | Sawp</title>
      {/* <meta name="description" content="Generated by create next app" />*/}
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container mx-auto flex justify-center">
      <TableSwap />
    </div>
  </>
);

export default Swap;
