import type { NextPage } from "next";
import Head from "next/head";
import TableSwap from "@/components/TableSwap";
import fetchData from "@/helpers/fetchData";
import { Coin } from "@/services/transforms/coins";

interface Props {
  coins: Coin[];
}

const Swap: NextPage<Props, any> = ({ coins }) => (
  <>
    <Head>
      <title>Belo | Swap</title>
      {/* <meta name="description" content="Generated by create next app" />*/}
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container mx-auto flex justify-center">
      <TableSwap coins={coins} />
    </div>
  </>
);

export async function getServerSideProps() {
  const response = await fetchData({
    method: "GET",
    url: `/api/coins`,
  });

  return { props: { coins: response.data } };
}

export default Swap;
